[tool.poetry]
name = "algopracticehub"
version = "0.1.0"
description = ""
authors = ["Niral Koradia <koradiya.niral@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
