name: CI

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
